name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup PHP with PCOV
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          ini-values: pcov.directory=src
          coverage: pcov
      - name: Install dependencies
        uses: php-actions/composer@v6
        with:
          php_version: '8.1'
      - name: Lint
        run:  vendor/bin/phpcs --standard=psr2 src/
      - name: Test
        run:  vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

      - uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: '*.clover'
          fail_ci_if_error: true # optional (default = false)
          verbose: true